apiVersion: v1
kind: Pod
metadata:
 name: resultapp-pod
 labels:
  name: resultapp-pod
  app: demo-votingapp
spec:
 containers:
  - name: result-app
    image: dockersamples/examplevotingapp_worker
    ports:
     - containerPort: 80